name: Check Chrome Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-chrome:
    runs-on: ubuntu-latest

    steps:
      - name: Check Chrome & Chromedriver versions
        run: |
          google-chrome --version
          chromedriver --version
