name: Run Selenium Tests

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create screenshots directory
        run: mkdir -p screenshots

      - name: Run Maven Tests
        run: mvn clean test

      - name: List screenshots directory contents
        if: always()
        run: ls -la screenshots/

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: screenshots/
