name: Run Selenium Tests

on:
  schedule:
    - cron: '30 1 * * *' 
  workflow_dispatch:     

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Selenium tests
        run: |
          echo "Your Selenium test commands go here"
          
      - name: Run Maven Tests
        run: mvn clean test

      - name: Upload Screenshots
        if: always() # Run this step even if the test fails
        uses: actions/upload-artifact@v3
        with:
          name: test-screenshots
          path: screenshots/
